CLEAR
TITLE Random Print
NEW INT YY 0
NEW INT XX 0
NEW INT FG 0
NEW INT BG 0
TASK NEW RepeatTask 4000
TASK ADD RepeatTask RANDOMIZEINT YY 1 {WINDOWHEIGHT}
TASK START RepeatTask
SET BUFFERDELAY = 0
:START
RANDOMIZEINT XX 1 {WINDOWWIDTH}
RANDOMIZEINT FG 1 15
RANDOMIZEINT BG 1 15
SETCURSOR {XX} {YY}
PRINT *
SLEEP 100
COLOR {FG} {BG}
EXEC START